spring:
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2-ui

---
account:
  secret: "${random.value}"
  number: "${random.int}"
  bignumber: "${random.long}"
  uuid: "${random.uuid}"
  number-less-than-ten: "${random.int(10)}"
  number-in-range: "${random.int[1024,65536]}"
  type:
    "[/k1]": "v1"
    "[/k2]": "v2"

---
pricing.enabled: true
pricing.first-booking: "apple"
pricing.second_booking: "banana"
pricing.levels: 1, 2, 3
pricing.account-type:
  "[/key1]": "value1"
  "[/key2]": "value2"
  "/key3": "value3"
pricing.roles:
  - USER
  - ADMIN